# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - apt update
    - apt install -y libpcap0.8-dev
    - go env -w GOPROXY="https://goproxy.io"
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
  - id: darwin-amd64
    goos:
      - darwin
    goarch:
      - amd64
    env:
      # - PKG_CONFIG_SYSROOT_DIR=/sysroot/macos/amd64
      # - PKG_CONFIG_PATH=/sysroot/macos/amd64/usr/local/Cellar/libpcap/1.10.1/lib/pkgconfig
      - CC=o64-clang
      - CXX=o64-clang++
  - id: darwin-arm64
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
  - id: linux-amd64
    goos:
      - linux
    goarch:
      - amd64
    # hooks:
    #   pre:
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: kkHAIKE
    name: grpcdump
