// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: grpcdump/test/pb/foo.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BarReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Q string `protobuf:"bytes,1,opt,name=Q,proto3" json:"Q,omitempty"`
}

func (x *BarReq) Reset() {
	*x = BarReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcdump_test_pb_foo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BarReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BarReq) ProtoMessage() {}

func (x *BarReq) ProtoReflect() protoreflect.Message {
	mi := &file_grpcdump_test_pb_foo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BarReq.ProtoReflect.Descriptor instead.
func (*BarReq) Descriptor() ([]byte, []int) {
	return file_grpcdump_test_pb_foo_proto_rawDescGZIP(), []int{0}
}

func (x *BarReq) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

type BarResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	R string `protobuf:"bytes,1,opt,name=R,proto3" json:"R,omitempty"`
}

func (x *BarResp) Reset() {
	*x = BarResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcdump_test_pb_foo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BarResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BarResp) ProtoMessage() {}

func (x *BarResp) ProtoReflect() protoreflect.Message {
	mi := &file_grpcdump_test_pb_foo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BarResp.ProtoReflect.Descriptor instead.
func (*BarResp) Descriptor() ([]byte, []int) {
	return file_grpcdump_test_pb_foo_proto_rawDescGZIP(), []int{1}
}

func (x *BarResp) GetR() string {
	if x != nil {
		return x.R
	}
	return ""
}

var File_grpcdump_test_pb_foo_proto protoreflect.FileDescriptor

var file_grpcdump_test_pb_foo_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x67, 0x72, 0x70, 0x63, 0x64, 0x75, 0x6d, 0x70, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2f,
	0x70, 0x62, 0x2f, 0x66, 0x6f, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x74, 0x65,
	0x73, 0x74, 0x22, 0x16, 0x0a, 0x06, 0x42, 0x61, 0x72, 0x52, 0x65, 0x71, 0x12, 0x0c, 0x0a, 0x01,
	0x51, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x51, 0x22, 0x17, 0x0a, 0x07, 0x42, 0x61,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0c, 0x0a, 0x01, 0x52, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x01, 0x52, 0x32, 0x29, 0x0a, 0x03, 0x46, 0x6f, 0x6f, 0x12, 0x22, 0x0a, 0x03, 0x42, 0x61,
	0x72, 0x12, 0x0c, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x42, 0x61, 0x72, 0x52, 0x65, 0x71, 0x1a,
	0x0d, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x42, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x42, 0x12,
	0x5a, 0x10, 0x67, 0x72, 0x70, 0x63, 0x64, 0x75, 0x6d, 0x70, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpcdump_test_pb_foo_proto_rawDescOnce sync.Once
	file_grpcdump_test_pb_foo_proto_rawDescData = file_grpcdump_test_pb_foo_proto_rawDesc
)

func file_grpcdump_test_pb_foo_proto_rawDescGZIP() []byte {
	file_grpcdump_test_pb_foo_proto_rawDescOnce.Do(func() {
		file_grpcdump_test_pb_foo_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpcdump_test_pb_foo_proto_rawDescData)
	})
	return file_grpcdump_test_pb_foo_proto_rawDescData
}

var file_grpcdump_test_pb_foo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpcdump_test_pb_foo_proto_goTypes = []interface{}{
	(*BarReq)(nil),  // 0: test.BarReq
	(*BarResp)(nil), // 1: test.BarResp
}
var file_grpcdump_test_pb_foo_proto_depIdxs = []int32{
	0, // 0: test.Foo.Bar:input_type -> test.BarReq
	1, // 1: test.Foo.Bar:output_type -> test.BarResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpcdump_test_pb_foo_proto_init() }
func file_grpcdump_test_pb_foo_proto_init() {
	if File_grpcdump_test_pb_foo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpcdump_test_pb_foo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BarReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcdump_test_pb_foo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BarResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpcdump_test_pb_foo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcdump_test_pb_foo_proto_goTypes,
		DependencyIndexes: file_grpcdump_test_pb_foo_proto_depIdxs,
		MessageInfos:      file_grpcdump_test_pb_foo_proto_msgTypes,
	}.Build()
	File_grpcdump_test_pb_foo_proto = out.File
	file_grpcdump_test_pb_foo_proto_rawDesc = nil
	file_grpcdump_test_pb_foo_proto_goTypes = nil
	file_grpcdump_test_pb_foo_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FooClient is the client API for Foo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FooClient interface {
	Bar(ctx context.Context, in *BarReq, opts ...grpc.CallOption) (*BarResp, error)
}

type fooClient struct {
	cc grpc.ClientConnInterface
}

func NewFooClient(cc grpc.ClientConnInterface) FooClient {
	return &fooClient{cc}
}

func (c *fooClient) Bar(ctx context.Context, in *BarReq, opts ...grpc.CallOption) (*BarResp, error) {
	out := new(BarResp)
	err := c.cc.Invoke(ctx, "/test.Foo/Bar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FooServer is the server API for Foo service.
type FooServer interface {
	Bar(context.Context, *BarReq) (*BarResp, error)
}

// UnimplementedFooServer can be embedded to have forward compatible implementations.
type UnimplementedFooServer struct {
}

func (*UnimplementedFooServer) Bar(context.Context, *BarReq) (*BarResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Bar not implemented")
}

func RegisterFooServer(s *grpc.Server, srv FooServer) {
	s.RegisterService(&_Foo_serviceDesc, srv)
}

func _Foo_Bar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BarReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FooServer).Bar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/test.Foo/Bar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FooServer).Bar(ctx, req.(*BarReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Foo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "test.Foo",
	HandlerType: (*FooServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Bar",
			Handler:    _Foo_Bar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpcdump/test/pb/foo.proto",
}
